apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
     app: nginx
spec:
  replicas: 1
  selector:
    matchlabels:
      app: nginx
template:
  metadata:
    labels:
      app: nginx
  spec:
    containers:
    - name: nginx
      image: nginx:1.6
      ports:
      - containerPort: 80
---
apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-service  
  labels:
    app: nginx
spec:
  type:NodePort
  ports:
    nodePort: 30500
    port: 80
    protocol: TCP
  selector:
    app: nginx
    

